on:
  push:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    env:
      BUNDLESIZE_GITHUB_TOKEN: 2c82a5661062648635f293dbe33667394c089b62
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Use Node.js
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.4.0

      - run: |
          npm install
          npm run build
          npm test
