on:
  push:

jobs:
  bundlesize:
    runs-on: ubuntu-latest
    env:
      BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Use Node.js
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.4.0

      - name:
        working-direction: subdir
        run: |
          npm install
          npm run build
          npm test
